### ISSUE TITLE
CSS Framework

### ISSUE THREAD

**Issue by HarvBCoding** [mateusverbar/gitmeadrink#2]
**Description**

- add mobility
- basic design (colors and columns)

**Comment by mateusverbar** [comment]
Definitely don't command flexbox like I'd like to yet, but I will fuss with this issue more tomorrow. Not crucial for Wednesday, but would still be nice to have a prettier html/css skeleton to load. My thought/goal was to have the h1 header be centered and the instructions centered underneath it in the header element. But I'm having trouble centering that <p> element underneath the header element in flexbox.

**Comment by HarvBCoding** [comment]
No worries! That's what bootstrap is for LOL I thought the site looked amazing! And I loved the color scheme you picked.

**Comment by mateusverbar** [comment]
Cool, I think I got the CSS looking right on mobile screens with flex and such so I'm gonna call this one closed (though lemme know if not!)
